@startuml Day20
[*] --> broadcaster
gv : %
gv --> lq
gv --> pm
rv : %
rv --> jd
rv --> nh
nh : %
nh --> rs
nh --> jd
vt : &
vt --> tj
zv : %
zv --> pm
zv --> gv
gh : %
gh --> jd
gh --> vd
hh : %
hh --> bf
hh --> qm
kx : %
kx --> nf
st : %
st --> pm
st --> zc
bh : %
bh --> qm
bh --> pv
sk : &
sk --> tj
hl : %
hl --> nf
hl --> pn
mt : %
mt --> st
mt --> pm
jd : &
jd --> ts
jd --> gh
jd --> vd
jd --> dc
jd --> xc
zm : %
zm --> hm
pv : %
pv --> vv
zf : %
zf --> nf
zf --> cz
xc : &
xc --> tj
bf : %
bf --> qm
ts : %
ts --> sg
ht : %
ht --> ch
ht --> nf
pb : %
pb --> rv
pb --> jd
nx : %
nx --> fc
mb : %
mb --> mt
mh : %
mh --> jd
mh --> pb
lc : %
lc --> bh
xg : %
xg --> mb
xg --> pm
vd : %
vd --> dc
broadcaster --> gh
broadcaster --> dl
broadcaster --> xg
broadcaster --> fb
sg : %
sg --> mh
sg --> jd
qq : %
qq --> ts
qq --> jd
dl : %
dl --> nf
dl --> sv
vv : %
vv --> sm
vv --> qm
zc : %
zc --> tb
sr : %
sr --> zv
sr --> pm
dc : %
dc --> gb
cz : %
cz --> nf
cz --> zm
rs : %
rs --> jd
hm : %
hm --> nf
hm --> hl
gd : %
gd --> sr
qm : &
qm --> lc
qm --> pv
qm --> nx
qm --> fb
qm --> kk
tj : &
tj --> rx
gb : %
gb --> qq
gb --> jd
xf : %
xf --> zf
tb : %
tb --> lg
sm : %
sm --> qm
sm --> hh
fb : %
fb --> dr
fb --> qm
lq : %
lq --> pm
nf : &
nf --> zm
nf --> dl
nf --> ch
nf --> xf
nf --> vt
pm : &
pm --> sk
pm --> zc
pm --> tb
pm --> gd
pm --> mb
pm --> xg
pn : %
pn --> nf
pn --> kx
fc : %
fc --> xb
fc --> qm
ch : %
ch --> xf
kk : &
kk --> tj
lg : %
lg --> pm
lg --> gd
sv : %
sv --> nf
sv --> ht
xb : %
xb --> qm
xb --> lc
dr : %
dr --> nx
dr --> qm
@enduml
